//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gen06_Rutas.ReferenciaMiServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaMiServicioWeb.ChoferesWSSoap")]
    public interface ChoferesWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse HelloWorld(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse> HelloWorldAsync(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminarChoferResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarChofer", ReplyAction="*")]
        Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse eliminarChofer(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarChofer", ReplyAction="*")]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse> eliminarChoferAsync(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarChofer", ReplyAction="*")]
        Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse insertarChofer(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarChofer", ReplyAction="*")]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse> insertarChoferAsync(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarChoferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarChofer", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequestBody Body;
        
        public eliminarChoferRequest() {
        }
        
        public eliminarChoferRequest(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarChoferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChoferId;
        
        public eliminarChoferRequestBody() {
        }
        
        public eliminarChoferRequestBody(int ChoferId) {
            this.ChoferId = ChoferId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarChoferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarChoferResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponseBody Body;
        
        public eliminarChoferResponse() {
        }
        
        public eliminarChoferResponse(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarChoferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string eliminarChoferResult;
        
        public eliminarChoferResponseBody() {
        }
        
        public eliminarChoferResponseBody(string eliminarChoferResult) {
            this.eliminarChoferResult = eliminarChoferResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarChoferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarChofer", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequestBody Body;
        
        public insertarChoferRequest() {
        }
        
        public insertarChoferRequest(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarChoferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apPaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apMaterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime fechaNac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string licencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string foto;
        
        public insertarChoferRequestBody() {
        }
        
        public insertarChoferRequestBody(string nombre, string apPaterno, string apMaterno, string telefono, System.DateTime fechaNac, string licencia, string foto) {
            this.nombre = nombre;
            this.apPaterno = apPaterno;
            this.apMaterno = apMaterno;
            this.telefono = telefono;
            this.fechaNac = fechaNac;
            this.licencia = licencia;
            this.foto = foto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarChoferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarChoferResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponseBody Body;
        
        public insertarChoferResponse() {
        }
        
        public insertarChoferResponse(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarChoferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertarChoferResult;
        
        public insertarChoferResponseBody() {
        }
        
        public insertarChoferResponseBody(string insertarChoferResult) {
            this.insertarChoferResult = insertarChoferResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChoferesWSSoapChannel : Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChoferesWSSoapClient : System.ServiceModel.ClientBase<Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap>, Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap {
        
        public ChoferesWSSoapClient() {
        }
        
        public ChoferesWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChoferesWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoferesWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChoferesWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.HelloWorld(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequestBody();
            Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse retVal = ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse> Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.HelloWorldAsync(Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldResponse> HelloWorldAsync() {
            Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.HelloWorldRequestBody();
            return ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.eliminarChofer(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest request) {
            return base.Channel.eliminarChofer(request);
        }
        
        public string eliminarChofer(int ChoferId) {
            Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequestBody();
            inValue.Body.ChoferId = ChoferId;
            Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse retVal = ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).eliminarChofer(inValue);
            return retVal.Body.eliminarChoferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse> Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.eliminarChoferAsync(Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest request) {
            return base.Channel.eliminarChoferAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferResponse> eliminarChoferAsync(int ChoferId) {
            Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.eliminarChoferRequestBody();
            inValue.Body.ChoferId = ChoferId;
            return ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).eliminarChoferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.insertarChofer(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest request) {
            return base.Channel.insertarChofer(request);
        }
        
        public string insertarChofer(string nombre, string apPaterno, string apMaterno, string telefono, System.DateTime fechaNac, string licencia, string foto) {
            Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apPaterno = apPaterno;
            inValue.Body.apMaterno = apMaterno;
            inValue.Body.telefono = telefono;
            inValue.Body.fechaNac = fechaNac;
            inValue.Body.licencia = licencia;
            inValue.Body.foto = foto;
            Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse retVal = ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).insertarChofer(inValue);
            return retVal.Body.insertarChoferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse> Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap.insertarChoferAsync(Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest request) {
            return base.Channel.insertarChoferAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferResponse> insertarChoferAsync(string nombre, string apPaterno, string apMaterno, string telefono, System.DateTime fechaNac, string licencia, string foto) {
            Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest inValue = new Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequest();
            inValue.Body = new Gen06_Rutas.ReferenciaMiServicioWeb.insertarChoferRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apPaterno = apPaterno;
            inValue.Body.apMaterno = apMaterno;
            inValue.Body.telefono = telefono;
            inValue.Body.fechaNac = fechaNac;
            inValue.Body.licencia = licencia;
            inValue.Body.foto = foto;
            return ((Gen06_Rutas.ReferenciaMiServicioWeb.ChoferesWSSoap)(this)).insertarChoferAsync(inValue);
        }
    }
}
